name: Deploy Flask App

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (opcional)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run tests (opcional si tienes tests)
        run: |
          echo "No hay pruebas aún"
          # python -m unittest discover tests/

      - name: Deploy to Render (via API or webhook)
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "Render Deploy Hook URL no está configurado. Aborting deployment."
            exit 1
          else
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          fi
